# Generated by Django 3.1.2 on 2020-10-06 16:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('publish_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
